//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vseved
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public Quiz()
        {
            this.WorkTask = new HashSet<WorkTask>();
        }
    
        public int Id { get; set; }
        public int Subject_Id { get; set; }
        public string Title { get; set; }
        public System.DateTime DateTimeStart { get; set; }
        public System.DateTime DateTimeEnd { get; set; }
        public bool MarkingType { get; set; }
        public System.DateTime recDateTime { get; set; }
        public bool recDeleted { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual ICollection<WorkTask> WorkTask { get; set; }
    }
}
